---
title: "Euks"
author: "CGA"
output: html_document
---

## Libraries

```{r}
library(tidyverse)
library(vegan)
```

## Data import

```{r data}
asv_table <- read.csv("C:/Users/Administrador/Desktop/Camilo/sentrynels/Data/DADA2/asv_table.csv", 
                      header = TRUE, 
                      skip = 0, 
                      sep = ";", 
                      fill = TRUE, 
                      row.names = 1)
# asv_table <- apply(asv_table, 2, function(x) as.numeric(as.integer(x))) %>% as.data.frame()
# skip unless necessary
samples <- c("C1A17", "C1F18", "C1A18", "C2A17", "C2F18", "C2A18", "C3A17", "C3F18", "C3A18", "C4A17", "C4F18", "C4A18", 
             "F1A17", "F1F18", "F1A18", "F2A17", "F2F18", "F2A18", "F3A17", "F3F18", "F3A18", "F4A17", "F4F18", "F4A18", 
             "H1A17", "H1F18", "H1A18", "H2A17", "H2F18", "H2A18", "H3A17", "H3F18", "H3A18", "H4A17", "H4F18", "H4A18", 
             "P1F18", "P1A18", "P2F18", "P3F18", "P4F18", 
             "Q1A17", "Q1F18", "Q2A17", "Q2F18", "Q3A17", "Q3F18", "Q3A18", "Q4A17", "Q4F18", "Q4A18", 
             "L1A17", "L1F18", "L1A18", "L2A17", "L2F18", "L2A18", "L3A17", "L3F18", "L3A18", "L4A17", "L4F18", "L4A18") #63
rownames(asv_table) <- samples
write.csv2(asv_table, "C:/Users/Administrador/Desktop/Camilo/sentrynels/Data/Characterization/ASV_table.csv")

taxa <- read.csv("C:/Users/Administrador/Desktop/Camilo/sentrynels/Data/DADA2/assigned_taxa.csv", 
                 header = TRUE,
                 sep = ";", 
                 skip = 0) %>% 
  dplyr::rename(Sequences = X) %>% 
  add_column(ASV = c(str_glue("ASV000{1:9}"), 
                     str_glue("ASV00{10:99}"), 
                     str_glue("ASV0{100:999}"), 
                     str_glue("ASV{1000:6192}")), 
             .after = "Sequences") # Lucas' solution
rownames(taxa) <- taxa[,1]
write.csv2(taxa, "C:/Users/Administrador/Desktop/Camilo/sentrynels/Data/Characterization/Taxa.csv")

# Sanity check LABMICMAR: if TRUE you can continue...
print(all(colnames(asv_table)%in%rownames(taxa)))
```

## NA filtering: first two levels ('Kingdom' and 'Supergroup')

```{r}
unassigned <- taxa[rowSums(is.na(taxa[,c(3,4)]))>0,] # 244 were not assigned at Kingdom and Supergroup levels
unknown <- taxa[rowSums(is.na(taxa[3]))>0,] # 29 of 244 were completely unclassified
euks <- taxa[!row.names(taxa)%in%unassigned[,1],]
write.csv2(euks, "C:/Users/Administrador/Desktop/Camilo/sentrynels/Data/Characterization/Eukaryotes_taxa.csv")
euks_asv <- dplyr::select(asv_table, -all_of(unassigned[,1]))
write.csv2(euks_asv, "C:/Users/Administrador/Desktop/Camilo/sentrynels/Data/Characterization/Eukaryotes_asv_tabla.csv")

print(all(colnames(euks_asv)%in%rownames(euks))) #If TRUE you can continue
```

## Rarefaction analysis

```{r}
sort_obs <- sort(rowSums(euks_asv))

png("/Users/Administrador/Desktop/Camilo/sentrynels/Analysis/Euks/Fig_1_Sequencing_saturation_eukaryotes_ASV.png")
par(mar = c(5.1, 4.1, 4.1, 2.1), oma = c(0, 0, 0, 0))
vegan::rarecurve(x = euks_asv, col = "orange", lwd = 2, las = 1, label = TRUE, step = 10, cex = 0.5)
dev.off()

rare_euks_asv <- vegan::rrarefy(euks_asv, sort_obs[1]) %>% as.data.frame()
png("/Users/Administrador/Desktop/Camilo/sentrynels/Analysis/Euks/Fig_2_Rarefacted_sequencing_saturation_eukaryotes_ASV.png")
par(mar = c(5.1, 4.1, 4.1, 2.1), oma = c(0, 0, 0, 0))
vegan::rarecurve(x = rare_euks_asv, col = "slateblue", lwd = 2, las = 1, label = TRUE, step = 10, cex = 0.5)
dev.off()
write.csv2(rare_euks_asv, "/Users/Administrador/Desktop/Camilo/sentrynels/Data/Characterization/Rarefacted_eukaryotes_asv_table.csv")
```

## Data management

```{r}
euks_complete <- as.data.frame(t(euks_asv))
euks_complete <- dplyr::mutate(euks_complete, Sequences = rownames(euks_complete), .before = "C1A17")
euks_complete <- dplyr::mutate(euks_complete, 
                               Chanaral = rowSums(euks_complete[2:13]), 
                               Flamenco = rowSums(euks_complete[14:25]), 
                               Huasco = rowSums(euks_complete[26:37]), 
                               Pta_Choros = rowSums(euks_complete[38:42]), 
                               Quintero = rowSums(euks_complete[43:52]), 
                               Las_Cruces = rowSums(euks_complete[53:64]), 
                               Total = rowSums(euks_complete[2:64])
                               )
euks_complete <- dplyr::inner_join(euks_complete, euks, by = "Sequences") %>% dplyr::relocate(ASV, .after = Sequences)
rownames(euks_complete) <- euks_complete[,2]
write.csv2(euks_complete, "/Users/Administrador/Desktop/Camilo/sentrynels/Data/Characterization/Eukaryotes_characterization.csv")
```

