---
title: "Core"
author: "CGA"
output: html_document
---

## Libraries

```{r}
library(tidyverse)
library(vegan)
library(UpSetR)
```

## Data import

```{r data}
euks_complete <- read.csv("/Documents/Proyectos_R/sentrynels/Data/Characterization/Eukaryotes_characterization.csv", 
                          header = TRUE, 
                          sep = ";", 
                          dec = ".", 
                          skip = 0, 
                          row.names = 1)
```

## Data edition

```{r}
euks_upset <- euks_complete[,-c(1:2,72:81)] %>% 
  vegan::decostand(method = "pa") %>% 
  add_column(Sequences = euks_complete$Sequences, 
             .before = "C1A17")
write.csv2(euks_upset, "/Documents/Proyectos_R/sentrynels/Data/Core/Upset_formated_eukaryotes_data.csv")
```

## UpSet visualization
### Complete

```{r}
png("/Documents/Proyectos_R/sentrynels/Analysis/Core/Fig_3_complete_upset_eukaryotes.png", width = 50, height = 23, units = "in", res = 300)
UpSetR::upset(euks_upset, 
              nsets = 6, 
              nintersects = NA, 
              sets = c("Las_Cruces", "Quintero", "Pta_Choros", "Huasco", "Flamenco", "Chanaral"), 
              empty.intersections = "on", 
              keep.order = TRUE, 
              point.size = 3.5, 
              line.size = 1.5, 
              text.scale = 2, 
              mainbar.y.label = "Sites Intersections", 
              sets.x.label = "ASVs per sampling site")
dev.off()
```

### Selected
```{r}
png("/Documents/Proyectos_R/sentrynels/Analysis/Core/Fig_4_selected_upset_intersections_eukaryotes.png", width = 40, height = 17, units = "in", res = 300)
UpSetR::upset(euks_upset, 
              nsets = 6, 
              nintersects = NA, 
              sets = c("Las_Cruces", "Quintero", "Pta_Choros", "Huasco", "Flamenco", "Chanaral"), 
              intersections = list("Las_Cruces", 
                                   "Quintero", 
                                   "Pta_Choros", 
                                   "Huasco", 
                                   "Flamenco", 
                                   "Chanaral", 
                                   list("Chanaral", "Flamenco"), 
                                   list("Huasco", "Pta_Choros"), 
                                   list("Quintero", "Las_Cruces"),
                                   list("Chanaral", "Huasco"), 
                                   list("Chanaral", "Quintero"), 
                                   list("Huasco", "Quintero"), 
                                   list("Flamenco", "Pta_Choros"),
                                   list("Flamenco", "Las_Cruces"), 
                                   list("Pta_Choros", "Las_Cruces"), 
                                   list("Quintero", "Las_Cruces"), 
                                   list("Chanaral", "Huasco", "Quintero"), 
                                   list("Flamenco", "Pta_Choros", "Las_Cruces"), 
                                   list("Chanaral", "Flamenco", "Huasco", "Pta_Choros"), 
                                   list("Chanaral", "Flamenco", "Huasco", "Pta_Choros", "Quintero"), 
                                   list("Chanaral", "Flamenco", "Huasco", "Pta_Choros", "Las_Cruces"), 
                                   list("Chanaral", "Flamenco", "Huasco", "Pta_Choros", "Quintero", "Las_Cruces")
                                   ), 
              empty.intersections = "on", 
              keep.order = TRUE, 
              query.legend = "top", 
              queries = list(list(query = intersects, params = "Chanaral", color = "#FF8811", active = TRUE, query.name = "Unique Chañaral ASVs"), 
                             list(query = intersects, params = "Flamenco", color = "#F4D06F", active = TRUE, query.name = "Unique Flamenco ASVs"), 
                             list(query = intersects, params = "Huasco", color = "#392F5A", active = TRUE, query.name = "Unique Huasco ASVs"), 
                             list(query = intersects, params = "Pta_Choros", color = "#403286", active = TRUE, query.name = "Unique Punta Choros ASVs"), 
                             list(query = intersects, params = "Quintero", color = "#18E0BD", active = TRUE, query.name = "Unique Quintero ASVs"), 
                             list(query = intersects, params = "Las_Cruces", color = "#80EB9F", active = TRUE, query.name = "Unique Las Cruces ASVs"), 
                             list(query = intersects, params = list("Chanaral", "Flamenco", "Huasco", "Pta_Choros", "Quintero", "Las_Cruces"), color = "#EF233C", active = TRUE, query.name = "Shared ASVs")
                             ), 
              point.size = 3.5, 
              line.size = 1.5, 
              text.scale = 3, 
              mainbar.y.label = "Sites Intersections", 
              sets.x.label = "ASVs per sampling site")
dev.off()
```

