---
title: "PPE"
author: "CGA"
output: html_document
---

## Libraries

```{r}
library(tidyverse)
library(vegan)
library(UpSetR)
library(hrbrthemes)
```

## Data import

```{r data}
euks_complete <- read.csv("https://raw.githubusercontent.com/cmlglvz/sentrynels/main/Data/Characterization/Eukaryotes_characterization.csv", 
                          header = TRUE, 
                          sep = ";", 
                          dec = ".", 
                          skip = 0, 
                          row.names = 1)
```

## Eukaryotes subsetting

```{r}
unique(euks_complete$Division) # At least 21 known phyla of eukaryotes in the dataset
autotrophic <- euks_complete %>% 
  dplyr::filter(Division == "Chlorophyta" | Division == "Stramenopiles" | Division == "Cryptophyta" | Division == "Cryptophyta:nucl" | Division == "Haptophyta" | Division == "Kathablepharidacea" | Division == "Rhodophyta") %>% dplyr::filter(Subdivision != "Bigyra")
write.csv2(autotrophic, "/Users/Administrador/Desktop/Camilo/sentrynels/Data/PPE/Autotrophic_eukaryotes_ASV.csv")
```

## PPE Selection

```{r}
oldie <- read.csv("/Users/Administrador/Desktop/Camilo/sentrynels/Data/PPE/HCS_PPE_edited_taxonomic_and_abundance.csv", 
                  header = TRUE, sep = ";", dec = ".", skip = 0)
ppes <- autotrophic[autotrophic$Sequences %in% oldie$Seq,]
write.csv2(ppes, "/Users/Administrador/Desktop/Camilo/sentrynels/Data/PPE/PPEs_ASV_table.csv")
```

## UpSet

### Data preparation
```{r}
ppe_upset <- ppes[,-c(1,2,72:81)] %>% 
  vegan::decostand(method = "pa") %>% 
  tibble::add_column(Sequences = ppes$Sequences, .before = "C1A17")
write.csv2(ppe_upset, "/Users/Administrador/Desktop/Camilo/sentrynels/Data/PPE/Upset_formated_PPE_data.csv")
```

### Plot

```{r}
png("/Users/Administrador/Desktop/Camilo/sentrynels/Analysis/PPEs/Fig_6_upset_intersections_ppe.png", width = 40, height = 17, units = "in", res = 300)
UpSetR::upset(ppe_upset, 
              nsets = 6, 
              nintersects = NA, 
              sets = c("Las_Cruces", "Quintero", "Pta_Choros", "Huasco", "Flamenco", "Chanaral"), 
              intersections = list("Las_Cruces", 
                                   "Quintero", 
                                   "Pta_Choros", 
                                   "Huasco", 
                                   "Flamenco", 
                                   "Chanaral", 
                                   list("Chanaral", "Flamenco"), 
                                   list("Huasco", "Pta_Choros"), 
                                   list("Quintero", "Las_Cruces"),
                                   list("Chanaral", "Huasco"), 
                                   list("Chanaral", "Quintero"), 
                                   list("Huasco", "Quintero"), 
                                   list("Flamenco", "Pta_Choros"),
                                   list("Flamenco", "Las_Cruces"), 
                                   list("Pta_Choros", "Las_Cruces"), 
                                   list("Quintero", "Las_Cruces"), 
                                   list("Chanaral", "Huasco", "Quintero"), 
                                   list("Flamenco", "Pta_Choros", "Las_Cruces"), 
                                   list("Chanaral", "Flamenco", "Huasco", "Pta_Choros"), 
                                   list("Chanaral", "Flamenco", "Huasco", "Pta_Choros", "Quintero"), 
                                   list("Chanaral", "Flamenco", "Huasco", "Pta_Choros", "Las_Cruces"), 
                                   list("Chanaral", "Flamenco", "Huasco", "Pta_Choros", "Quintero", "Las_Cruces")
                                   ), 
              empty.intersections = "on", 
              keep.order = TRUE, 
              query.legend = "top", 
              queries = list(list(query = intersects, params = "Chanaral", color = "#FF8811", active = TRUE, query.name = "Unique Chañaral ASVs"), 
                             list(query = intersects, params = "Flamenco", color = "#F4D06F", active = TRUE, query.name = "Unique Flamenco ASVs"), 
                             list(query = intersects, params = "Huasco", color = "#392F5A", active = TRUE, query.name = "Unique Huasco ASVs"), 
                             list(query = intersects, params = "Pta_Choros", color = "#403286", active = TRUE, query.name = "Unique Punta Choros ASVs"), 
                             list(query = intersects, params = "Quintero", color = "#18E0BD", active = TRUE, query.name = "Unique Quintero ASVs"), 
                             list(query = intersects, params = "Las_Cruces", color = "#80EB9F", active = TRUE, query.name = "Unique Las Cruces ASVs"), 
                             list(query = intersects, params = list("Chanaral", "Flamenco", "Huasco", "Pta_Choros", "Quintero", "Las_Cruces"), color = "#EF233C", active = TRUE, query.name = "Shared ASVs")
                             ), 
              point.size = 3.5, 
              line.size = 1.5, 
              text.scale = 3, 
              mainbar.y.label = "Sites Intersections", 
              sets.x.label = "ASVs per sampling site")
dev.off()
```

## ASV identification

### Shared (Core)
```{r}
core <- ppe_upset %>% 
  dplyr::filter(Chanaral == 1 & Flamenco == 1 & Huasco == 1 & Pta_Choros == 1 & Quintero == 1 & Las_Cruces == 1)
core_abundance <- ppes[row.names(ppes)%in%row.names(core),]
write.csv2(core_abundance, "/Users/Administrador/Desktop/Camilo/sentrynels/Data/PPE/Ppe_core_asv_abundance.csv")
sum(core_abundance[,72])
```
### Uniques per site

```{r}
chanaral <- ppe_upset %>% 
  dplyr::filter(Chanaral == 1 & Flamenco == 0 & Huasco == 0 & Pta_Choros == 0 & Quintero == 0 & Las_Cruces == 0)
chanaral_abundance <- ppes[row.names(ppes)%in%row.names(chanaral),]

flamenco <- ppe_upset %>% 
  dplyr::filter(Chanaral == 0 & Flamenco == 1 & Huasco == 0 & Pta_Choros == 0 & Quintero == 0 & Las_Cruces == 0)
flamenco_abundance <- ppes[row.names(ppes)%in%row.names(flamenco),]

huasco <- ppe_upset %>% 
  dplyr::filter(Chanaral == 0 & Flamenco == 0 & Huasco == 1 & Pta_Choros == 0 & Quintero == 0 & Las_Cruces == 0)
huasco_abundance <- ppes[row.names(ppes)%in%row.names(huasco),]

pta_choros <- ppe_upset %>% 
  dplyr::filter(Chanaral == 0 & Flamenco == 0 & Huasco == 0 & Pta_Choros == 1 & Quintero == 0 & Las_Cruces == 0)
ptachoros_abundance <- ppes[row.names(ppes)%in%row.names(pta_choros),]

quintero <- ppe_upset %>% 
  dplyr::filter(Chanaral == 0 & Flamenco == 0 & Huasco == 0 & Pta_Choros == 0 & Quintero == 1 & Las_Cruces == 0)
quintero_abundance <- ppes[row.names(ppes)%in%row.names(quintero),]

las_cruces <- ppe_upset %>% 
  dplyr::filter(Chanaral == 0 & Flamenco == 0 & Huasco == 0 & Pta_Choros == 0 & Quintero == 0 & Las_Cruces == 1)
lascruces_abundance <- ppes[row.names(ppes)%in%row.names(las_cruces),]
```

## Groups abundance

```{r}
asv_types <- read.csv("/Users/Administrador/Desktop/Camilo/sentrynels/Data/PPE/PPE_ASV_type_abundance.csv", 
                      header = TRUE, 
                      sep = ";", 
                      skip = 0) %>% 
  dplyr::rename(Site = X)
asv_types$Site <- factor(asv_types$Site, levels = c("Chanaral", "Flamenco", "Huasco", "Pta_Choros", "Quintero", "Las_Cruces"))
# Transform into long dataframe for ploting
long_types <- reshape2::melt(asv_types[,-5], id.vars = "Site", variable.name = "Type") %>% dplyr::rename(Abundance = value) # you can use pivot_longer() instead
long_types$Type <- factor(long_types$Type, levels = c("Unique", "Other", "Shared"))
```

## Abundance plot

```{r}
aplot <- ggplot(long_types, 
                aes(x = Site, 
                    y = Abundance, 
                    fill = Type)) + 
  geom_bar(position = "fill", stat = "identity") + 
  labs(x = "Sites", 
       y = "Relative Abundance", 
       title = "Relative contribution of PPE ASV grouped by presence at sites") + 
  scale_fill_manual(values = c("#9CAFB7", "#2B2D42", "#EF233C")) + 
  theme_ipsum(base_size = 22, 
              axis_title_size = 25, 
              plot_title_size = 25) + 
  theme(legend.position = "bottom", 
        legend.direction = "horizontal")
ggsave(plot = aplot, 
       filename = "Fig_7_relative_contribution_ASV_eukaryotes_by_type.png", 
       path = "/Users/Administrador/Desktop/Camilo/sentrynels/Analysis/PPEs/", 
       width = 23, 
       height = 15, 
       dpi = 600)
```

