---
title: "Diversity_CORE"
author: "CGA"
output: html_document
---

## Libraries

```{r,echo=FALSE,include=FALSE,warning=FALSE,message=FALSE}
library(tidyverse)
library(vegan)
library(viridis)
library(hrbrthemes)
```

## Data import

```{r data}
core_complete <- read.csv("https://raw.githubusercontent.com/cmlglvz/sentrynels/main/Data/PPE/Ppe_core_asv_abundance.csv", 
                          header = TRUE, 
                          sep = ";", 
                          skip = 0, 
                          row.names = 1)
environmental <- read.csv("https://raw.githubusercontent.com/cmlglvz/sentrynels/main/Data/Diversity/Environmental_data.csv", 
                           header = TRUE, 
                           sep = ";", 
                           dec = ".", 
                           skip = 0,
                           row.names = 1)
environmental$Site <- factor(environmental$Site, levels = as.character(unique(environmental$Site)))
```

## Data edition

```{r}
abundance <- core_complete[,c(3:65)] %>% t() %>% as.data.frame()
taxa <- core_complete[,-c(3:72)]
```

## Richness

```{r}
richness <- with(environmental, estimateR(abundance, Site)) %>% 
  t() %>% as.data.frame() %>% 
  add_column(Site = environmental$Site, .name_repair = "minimal")
write.csv(richness, "/Users/Administrador/Desktop/Camilo/sentrynels/Data/Diversity/core_richness.csv")
```

### Chao1

```{r}
chao1 <- richness %>% 
  rename("Chao1" = "S.chao1") %>% 
  ggplot(aes(x = Site,
             y = Chao1,
             fill = Site)) + 
  geom_violin(width = 1.2) + 
  geom_boxplot(width = 0.2, 
               color = "grey", 
               alpha = 0.7) + 
  scale_fill_viridis(discrete = TRUE) + 
  geom_jitter(color = "#4C443C", 
              size = 1, 
              alpha = 0.6) +
  theme_ipsum() + 
  theme(legend.position = "none") + 
  ggtitle("Chao1 richness")
ggsave(plot = chao1,
       filename = "Fig_27_core_chao1_richness.png", 
       path = "/Users/Administrador/Desktop/Camilo/sentrynels/Analysis/Diversity/", 
       width = 15, 
       height = 9, 
       dpi = 600)
```

### ACE

```{r}
ace <- richness %>% 
  rename("ACE" = "S.ACE") %>% 
  ggplot(aes(x = Site,
             y = ACE,
             fill = Site)) + 
  geom_violin(width = 1.2) + 
  geom_boxplot(width = 0.2, 
               color = "grey", 
               alpha = 0.7) + 
  scale_fill_viridis(discrete = TRUE) + 
  geom_jitter(color = "#4C443C", 
              size = 1, 
              alpha = 0.6) +
  theme_ipsum() + 
  theme(legend.position = "none") + 
  ggtitle("ACE richness")
ggsave(plot = ace,
       filename = "Fig_28_core_ACE_richness.png", 
       path = "/Users/Administrador/Desktop/Camilo/sentrynels/Analysis/Diversity/", 
       width = 15, 
       height = 9, 
       dpi = 600)
```

## Shannon

```{r}
shannon <- diversity(abundance, index = "shannon", equalize.groups = FALSE) %>% 
  as.matrix() %>% as.data.frame() %>% add_column(Site = environmental$Site, .name_repair = "minimal") %>% 
  rename("Shannon" = V1)
write.csv(shannon, "/Users/Administrador/Desktop/Camilo/sentrynels/Data/Diversity/core_shannon.csv")
shplot <- shannon %>% 
  ggplot(aes(x = Site, 
             y = Shannon, 
             fill = Site)) + 
  geom_violin(width = 1.1) + 
  geom_boxplot(width = 0.1, 
               color = "white", 
               alpha = 0.3) + 
  scale_fill_viridis(discrete = TRUE, alpha = 0.8) + 
  geom_jitter(color = "#4C443C", 
              size = 1, 
              alpha = 0.6) + 
  theme_ipsum() + 
  theme(legend.position = "none") + 
  ggtitle("Shannon diversity")
ggsave(plot = shplot,
       filename = "Fig_29_core_shannon_diversity.png", 
       path = "/Users/Administrador/Desktop/Camilo/sentrynels/Analysis/Diversity/", 
       width = 15, 
       height = 9, 
       dpi = 600)
```

## Simpson

```{r}
simpson <- diversity(abundance, index = "simpson", equalize.groups = FALSE) %>% 
  as.matrix() %>% as.data.frame() %>% add_column(Site = environmental$Site, .name_repair = "minimal") %>% 
  rename("Simpson" = V1)
write.csv(simpson, "/Users/Administrador/Desktop/Camilo/sentrynels/Data/Diversity/core_simpson.csv")
simplot <- simpson %>% 
  ggplot(aes(x = Site, 
             y = Simpson, 
             fill = Site)) + 
  geom_violin(width = 1.1) + 
  geom_boxplot(width = 0.1, 
               color = "white", 
               alpha = 0.3) + 
  scale_fill_viridis(discrete = TRUE, alpha = 0.8) + 
  geom_jitter(color = "#4C443C", 
              size = 1, 
              alpha = 0.6) + 
  theme_ipsum() + 
  theme(legend.position = "none") + 
  ggtitle("Simpson diversity")
ggsave(plot = simplot,
       filename = "Fig_30_core_simpson_diversity.png", 
       path = "/Users/Administrador/Desktop/Camilo/sentrynels/Analysis/Diversity/", 
       width = 15, 
       height = 9, 
       dpi = 600)
```

## Invsimpson

```{r}
inv <- diversity(abundance, index = "invsimpson", equalize.groups = FALSE) %>% 
  as.matrix() %>% as.data.frame() %>% add_column(Site = environmental$Site, .name_repair = "minimal") %>% 
  rename("Invsimpson" = V1)
write.csv(inv, "/Users/Administrador/Desktop/Camilo/sentrynels/Data/Diversity/core_invsimpson_data.csv")
iplot <- inv %>% 
  ggplot(aes(x = Site, 
             y = Invsimpson, 
             fill = Site)) + 
  geom_violin(width = 1.1) + 
  geom_boxplot(width = 0.1, 
               color = "white", 
               alpha = 0.3) + 
  scale_fill_viridis(discrete = TRUE, alpha = 0.8) + 
  geom_jitter(color = "#4C443C", 
              size = 1, 
              alpha = 0.6) + 
  theme_ipsum() + 
  theme(legend.position = "none") + 
  ggtitle("Invsimpson diversity")
ggsave(plot = iplot,
       filename = "Fig_31_core_invsimpson_diversity.png", 
       path = "/Users/Administrador/Desktop/Camilo/sentrynels/Analysis/Diversity/", 
       width = 15, 
       height = 9, 
       dpi = 600)
```

### Alternative

```{r}
unbiased <- simpson.unb(x = abundance) %>% 
  as.matrix() %>% as.data.frame() %>% add_column(Site = environmental$Site, .name_repair = "minimal") %>% 
  rename("Unbiased" = V1)
write.csv(unbiased, "/Users/Administrador/Desktop/Camilo/sentrynels/Data/Diversity/core_unbiased_simpson.csv")
unbplot <- unbiased %>% 
  ggplot(aes(x = Site, 
             y = Unbiased, 
             fill = Site)) + 
  geom_violin(width = 1.1) + 
  geom_boxplot(width = 0.1, 
               color = "white", 
               alpha = 0.3) + 
  scale_fill_viridis(discrete = TRUE, alpha = 0.8) + 
  geom_jitter(color = "#4C443C", 
              size = 1, 
              alpha = 0.6) + 
  labs(y = "Unbiased Simpson index") + 
  theme_ipsum() + 
  theme(legend.position = "none") + 
  ggtitle("Unbiased simpson richness")
ggsave(plot = unbplot,
       filename = "Fig_32_core_unbiased_simpson_diversity.png", 
       path = "/Users/Administrador/Desktop/Camilo/sentrynels/Analysis/Diversity/", 
       width = 15, 
       height = 9, 
       dpi = 600)
```

